# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a752f91ccbc4e33f6fe053638d7d6ec05c7650b8dc0bbf2efc72623f25f15c8b981d9968dcac43b406b20ebc9ab880ed78241f278d55cc7377865a74c33d995b

test:
  secret_key_base: 2078b4c4d73c390ef29cdd619fa77379411d7235e17a1fe7b8dbd0bdbf319f93f7aeb905e6c3f38410424360ef8c500f856b22f69ba60295732c8f5306b151f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
